openapi: 3.0.0
info:
  title: API Documentation
  description: API for managing products, users, orders, and reviews
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

tags:
  - name: Products
    description: Products endpoint
  - name: Users
    description: Users endpoint
  - name: Orders
    description: Orders endpoint

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: 1234567890
        name:
          type: string
          example: Product Name
        slug:
          type: string
          example: product-slug
        description:
          type: string
          example: Product Description
        image:
          type: string
          example: https://example.com/image.jpg
        images:
          type: array
          items:
            type: string
            example: https://example.com/image.jpg
        countInStock:
          type: integer
          example: 10
        isAvailable:
          type: boolean
          example: true
        brand:
          type: string
          example: Brand Name
        category:
          type: string
          example: Category Name
        rating:
          type: number
          example: 4.5
        numReviews:
          type: integer
          example: 10
        price:
          type: number
          example: 10.99
        discount:
          type: number
          example: 10
        discountedPrice:
          type: string
          example: 10.01

    User:
      type: object
      properties:
        id:
          type: string
          example: 1234567890
        name:
          type: string
          example: User Name
        email:
          type: string
          example: user@example.com
        photo:
          type: string
          example: https://example.com/image.jpg
        role:
          type: string
          example: user
        active:
          type: boolean
          example: true

    Order:
      type: object
      properties:
        id:
          type: string
          example: 1234567890
        user:
          $ref: "#/components/schemas/User"
        orderItems:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
        shippingAddress:
          type: object
          properties:
            province:
              type: string
              example: Province Name
            city:
              type: string
              example: City Name
            street:
              type: string
              example: Street Name
        paymentMethod:
          type: string
          example: Payment Method
        itemsPrice:
          type: number
          example: 10.99
        shippingPrice:
          type: number
          example: 10.99
        taxPrice:
          type: number
          example: 10.99
        totalPrice:
          type: number
          example: 10.99
        isPaid:
          type: boolean
          example: true
        isDelivered:
          type: boolean
          example: true
        paidAt:
          type: string
          format: date-time
          example: 2022-01-01T12:00:00.000Z
        deliveredAt:
          type: string
          format: date-time
          example: 2022-01-01T12:00:00.000Z

    OrderItem:
      type: object
      properties:
        id:
          type: string
          example: 1234567890
        product:
          $ref: "#/components/schemas/Product"
        qty:
          type: integer
          example: 10

    Review:
      type: object
      properties:
        id:
          type: string
          example: 1234567890
        product:
          $ref: "#/components/schemas/Product"
        user:
          $ref: "#/components/schemas/User"
        comment:
          type: string
          example: Review Comment
        rating:
          type: integer
          example: 5
#
# securitySchemes:
#   bearerAuth:
#     type: http
#     scheme: bearer
#     bearerFormat: JWT
